### ISSUE TITLE
TypeError: Error.captureStackTrace is not a function

### ISSUE THREAD

**Issue by davevilela** [octet-stream/slate-to-react#1] opened 2023-04-18 18:15 UTC
Hello, i'm having this exception whenever i try to render a slate document:
Uncaught TypeError: Error.captureStackTrace is not a function
    c slate-to-react.mjs:1
    d slate-to-react.mjs:1
    U slate-to-react.mjs:1
    W slate-to-react.mjs:1
    X slate-to-react.mjs:1
    X slate-to-react.mjs:1
    Y slate-to-react.mjs:1
    Z slate-to-react.mjs:1
    React 3
    Z slate-to-react.mjs:1
    te slate-to-react.mjs:1
    React 12
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
slate-to-react.mjs:1:262

**Comment by octet-stream** [comment] 2023-04-18 18:42
Oh, right, I forgot this is V8 only method. Sorry about that, lemme just disable it :)

**Comment by octet-stream** [comment] 2023-04-18 18:55
The fix available in https://github.com/octet-stream/slate-to-react/releases/tag/v0.7.2

**Comment by octet-stream** [comment] 2023-04-18 22:48
I've forgotten I left another `Error.captureStackTrace` in another place. The issue is resolved in https://github.com/octet-stream/slate-to-react/releases/tag/v0.7.4

Tried out in Safari and Firefox.
See in [codesandbox](https://codesandbox.io/p/sandbox/immutable-voice-e2vo05?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A7%2C%22endLineNumber%22%3A17%2C%22startColumn%22%3A7%2C%22startLineNumber%22%3A17%7D%5D). Just uncomment 16-31 lines. Then save file and it will show you `NoMatcherError` instead of `TypeError`.

**Comment by octet-stream** [comment] 2023-04-20 20:25
I'm gonna close this, your issue must be resolved.

**Closed by octet-stream** 2023-04-20 20:25 UTC
Labels: bug

**Comment by davevilela** [comment] 2023-04-24 13:27
@octet-stream thanks !
