### ISSUE TITLE
Does this work with react native?

### ISSUE THREAD

**Issue by davevilela** [octet-stream/slate-to-react#2] opened 2023-05-26 00:48 UTC
Anyone tried using this in react native?

**Comment by octet-stream** [comment] 2023-05-28 10:37
Never tried RN myself. What problems do you have specifically?

**Comment by davevilela** [comment] 2023-05-29 14:47
> Never tried RN myself. What problems do you have specifically?

I notice that the package has react-dom as a dependency, so I wonder if it would be possible to use this by overriding the default transforms and using native views instead.

**Comment by davevilela** [comment] 2023-05-29 15:32
![Screenshot 2023-05-29 at 12 24 43](https://github.com/octet-stream/slate-to-react/assets/18126630/0b0f3fe2-9942-45c7-93c7-c8ab5f00142c)
I tried putting a prototype together, but it seems that slate itself has problems with react-native...

**Comment by davevilela** [comment] 2023-05-29 15:40
![Screenshot 2023-05-29 at 12 40 17](https://github.com/octet-stream/slate-to-react/assets/18126630/d33d0a07-18ad-429d-a0aa-b06e50f892ce)
Some more updates: Now it appears that the crypto dependency is the problem

**Comment by octet-stream** [comment] 2023-05-29 15:48
Yes, you need to polyfill crypto youself. See: https://github.com/ai/nanoid#react-native

However, I'm willing to get rid of id generators by the 1.x or 2.x, so that would not be the problem in a future. The `id` field will be required, because I use it to provide React elements with `key` property, and the key must stay stable for better performance.

**Comment by octet-stream** [comment] 2023-05-29 15:53
> I notice that the package has react-dom as a dependency, so I wonder if it would be possible to use this by overriding the default transforms and using native views instead.

The package has only one dependency as of now - `nanoid`. Both `react` and `react-dom` are **peer** dependencies, and I'm actually relying only on `react` itself. So I think this shouldn't be the problem, if `react` package is compatible with RN.

**Comment by octet-stream** [comment] 2023-05-29 15:53
Also, I only use `Fragment` and `createElement` from `react`.

**Comment by davevilela** [comment] 2023-05-29 17:32
@octet-stream Got it to work! The polyfill solved the issue

**Comment by octet-stream** [comment] 2023-05-30 01:14
Glad to hear that. I think it would be great to add section about React Native integration in documentation.

Do default transforms work with RN? All of them are HTML elements and afaik RN uses native views to render elements, which mean, by my understanding, they should not work.

**Comment by davevilela** [comment] 2023-06-11 18:44
@octet-stream no, the default transforms do not work. I replaced them for native views and it's working as intended.

**Comment by octet-stream** [comment] 2023-06-26 07:35
Got it, thanks.
So, I think the issue is resolved, so I'm closing it.

**Closed by octet-stream** 2023-06-26 07:35 UTC
Labels: question
